export {default as Hero} from "./Hero"
export {default as Catigories} from "./Catigories"
export {default as ProductSection} from "./ProductSection"
export {default as Header} from "./Header"
export {default as Footer} from "./Footer"
export {default as AboutHero} from "./AboutHero"
export {default as OurBrands} from "./OurBrands"